TC 11-12
friends-library/thomas-chalkley pull request #5
Opened 2021-07-01 18:09 UTC by maijapapaya

@jaredh159 @Henderjay

2021-07-01 18:12 UTC, maijapapaya commented
I'm not sure what to do with "The Supplement" part near line 960. Maybe it's okay, but I thought it looked a little funky.

2021-07-02 15:02 UTC, Henderjay requested changes
You just forgot one [.numbered] tag above "sixth" in the modernized. And when you get to the Supplement at the bottom, I think we should use [.old-style] again, so that the heading and subheading are centered. Also... the comment in brackets just above The Supplement, let's give that an [.offset]

2021-07-02 15:02 UTC, Henderjay commented on journal/modernized/11-chapter-11.adoc
> +_Sixth;_
You forgot the [.numbered] here 👍🏻

2021-07-04 21:31 UTC, merged

2021-07-04 21:32 UTC, Henderjay commented
looks good, merged.